% =========================================================
% Read existing volume files AND mesh files, then solve arbitrary Tet4 DVC.
% Run: demo_userMesh_tetrahedron. No mesh is generated by this demo.
% =========================================================
clear; clc;
root=fileparts(mfilename('fullpath')); addpath(root);
%% Section 1: Read image and mesh filenames
sampleFolder=fullfile(root,'sample_userMesh_tetrahedron');
referenceFile=fullfile(sampleFolder,'vol_reference_tetrahedron.mat');
deformedFile=fullfile(sampleFolder,'vol_deformed_tetrahedron.mat');
meshSource=fullfile(sampleFolder,'mesh_userMesh_tetrahedron.mat');
% Alternative: numeric text files containing node/element IDs:
% meshSource=struct('nodesFile',fullfile(sampleFolder,'nodes_userMesh_tetrahedron.csv'), ...
%     'elementsFile',fullfile(sampleFolder,'elements_userMesh_tetrahedron.csv'));
%% Section 2: Parameters (mesh coordinates already use image voxel units)
DVCpara=struct('alpha',0.1,'tol',1e-4,'maxIter',100,'StrainType',0, ...
    'normalizeImages',true,'plotResults',true, ...
    'meshScale',[1 1 1],'meshOffset',[0 0 0]);
U0=[]; % Zero initial displacement; optional 3*N vector in input node order.
%% Section 3: Read mesh and solve (no mesh generation)
result=main_FE_GlobalDVC_userMesh_tetrahedron(referenceFile,deformedFile,meshSource,DVCpara,U0);
disp('Mean displacement [u,v,w] in voxels:'); disp(mean(reshape(result.U,3,[]),2)');
%% Section 4: Save results, retaining input node and element IDs
save(fullfile(root,'results_userMesh_tetrahedron.mat'),'result');
writematrix(result.nodalDisplacement,fullfile(root,'displacement_userMesh_tetrahedron.csv'));
% CSV columns: original_node_ID, u, v, w (voxel units).
